/**
 * Confidence level of the evidence gathered for a particular metric or assessment.
 */
export type ConfidenceLevel =
  | 'strong_evidence'
  | 'moderate_evidence'
  | 'low_evidence'
  | 'observability_gap'
  | 'insufficient_data';

/**
 * Target engineering seniority tier.
 */
export type SeniorityTier = 'intern' | 'junior' | 'mid' | 'senior' | 'staff' | 'principal' | string;

/**
 * Mandatory confidence text formats corresponding to each ConfidenceLevel.
 * Enforces strict compliance with the evidence brief output requirements.
 */
export type StrongEvidenceText = `Demonstrated across ${number} repositories and ${number} months — high confidence.`;
export type ModerateEvidenceText = 'Evidenced in limited context — probe in interview to confirm depth.';
export type LowEvidenceText = 'One instance detected — insufficient to score. Treat as unconfirmed in hiring decision.';
export type ObservabilityGapText = `No public evidence — likely private or enterprise context. Do not penalise. Recommend: ${string}`;
export type InsufficientDataText = 'This profile cannot be assessed from available public signals. Do not use this report as a filter for this candidate. Proceed directly to technical interview using the generated interview questions.';

/**
 * Union type matching any of the mandatory confidence text formats.
 */
export type ConfidenceText =
  | StrongEvidenceText
  | ModerateEvidenceText
  | LowEvidenceText
  | ObservabilityGapText
  | InsufficientDataText;

/**
 * Classifications for the level of AI leverage demonstrated by the engineer.
 */
export type AILeverageClass =
  | 'ai_operator'
  | 'ai_architect'
  | 'ai_passenger'
  | 'traditional_engineer'
  | 'disclosure_flag';

/**
 * Represents verified employment history and the technical rung achieved in previous roles.
 */
export interface EmploymentVerification {
  /**
   * Name of the verified employer.
   */
  employer: string;
  /**
   * Core rung/level achieved within the technical hierarchy (0 to 3).
   */
  rungAchieved: 0 | 1 | 2 | 3;
  /**
   * Human-readable label/description corresponding to the rung achieved.
   */
  rungText: string;
}

/**
 * Flags generated by anomaly detection algorithms to identify potential profile gaming or security concerns.
 */
export interface AntiGamingFlag {
  /**
   * The type of gaming or anomaly detected.
   */
  type:
    | 'commit_inflation'
    | 'fork_dumping'
    | 'burst_dormancy'
    | 'repo_laundering'
    | 'ai_generation_gap'
    | 'credential_leak';
  /**
   * Severity level of the flag, indicating potential risk weight in hiring evaluation.
   */
  severity: 'hard_stop' | 'soft_concern';
  /**
   * Verifiable evidence supporting the flag generation.
   */
  evidence: string;
  /**
   * Confidence score of the detection algorithm (e.g. 0.0 to 1.0).
   */
  confidenceScore: number;
  /**
   * Specific interview question/probe to verify or falsify this detection.
   */
  interviewProbe: string;
  /**
   * Hard stop auto-rejection setting. Always false for manual/holistic review.
   */
  autoReject: false;
}

/**
 * Raw metric assessment representing a specialized dimension of developer behavior.
 */
export interface PrimitiveAssessment {
  /**
   * Numeric score achieved in this metric, or null if insufficient data to score.
   */
  score: number | null;
  /**
   * Confidence level of the metric assessment.
   */
  confidence: ConfidenceLevel;
  /**
   * Mandatory confidence text corresponding to the confidence level.
   * Must conform to one of the predefined formats represented by {@link ConfidenceText}.
   */
  confidenceText: ConfidenceText | string;
  /**
   * Concrete, verifiable evidence list justifying the assessment.
   */
  keyEvidence: string[];
  /**
   * Specific areas where data is missing due to private repos or low activity.
   */
  observabilityGaps: string[];
  /**
   * Interview questions designed to probe this specific metric during hiring.
   */
  interviewProbes: string[];
}

/**
 * Supporting interface for Section A representing a single demonstrated capability and its evidence.
 */
export interface CapabilityEvidence {
  capability: string;
  evidence: string;
}

/**
 * Verifiable evidence of programming language usage and proficiency.
 */
export interface LanguageEvidence {
  /**
   * Name of the programming language.
   */
  name: string;
  /**
   * Whether the candidate explicitly claimed proficiency in this language.
   */
  claimed: boolean;
  /**
   * Whether concrete commit evidence was found for this language.
   */
  evidenced: boolean;
  /**
   * Optional rank of commit volume for this language relative to others (e.g., 1 is highest volume).
   */
  commitVolumeRank?: number;
  /**
   * Estimated active years writing this language based on commit history timestamps.
   */
  yearsActive?: number;
}

/**
 * Verifiable evidence of framework usage and proficiency.
 */
export interface FrameworkEvidence {
  /**
   * Name of the framework (e.g., React, Next.js, Express, Django).
   */
  name: string;
  /**
   * Whether the candidate explicitly claimed proficiency in this framework.
   */
  claimed: boolean;
  /**
   * Whether concrete commit or dependency file evidence was found.
   */
  evidenced: boolean;
  /**
   * Estimated active years with the framework based on commit history.
   */
  yearsActive?: number;
}

/**
 * Verifiable evidence of infrastructure, deployment, and cloud technology usage.
 */
export interface InfrastructureEvidence {
  /**
   * Name of the infrastructure/cloud technology (e.g., AWS, Terraform, Docker, Kubernetes).
   */
  name: string;
  /**
   * Whether the candidate explicitly claimed proficiency in this infrastructure technology.
   */
  claimed: boolean;
  /**
   * Whether concrete configuration or deployment script evidence was found.
   */
  evidenced: boolean;
  /**
   * Estimated active years with the infrastructure technology.
   */
  yearsActive?: number;
}

/**
 * Detailed qualitative dimension representing an area of engineering behavior.
 */
export interface QualitativeDimension {
  /**
   * Narrative description of the candidate's style and execution in this dimension.
   */
  summary: string;
  /**
   * Concrete commit hashes, pull requests, or code snippets supporting this qualitative evaluation.
   */
  examples: string[];
  /**
   * The underlying quantitative primitive assessment.
   */
  assessment: PrimitiveAssessment;
}

/**
 * Section A: Core Profile & Capabilities Summary.
 * Provides the overarching operating archetype, validated capabilities, AI leverage, and employment verification summary.
 */
export interface SectionA {
  /**
   * The dominant technical/operating style archetype of the candidate.
   * Examples: 'Productive Architect', 'Individual Contributor', 'Rapid Prototyper'.
   */
  operatingStyleArchetype: string;
  /**
   * Top three engineering capabilities demonstrated in the analysis, along with the supporting evidence.
   */
  topThreeCapabilities: CapabilityEvidence[];
  /**
   * Classification of the candidate's use and integration of AI in their development workflow.
   */
  aiLeverageClassification: AILeverageClass;
  /**
   * List of verified employers and the technical rungs achieved.
   */
  employmentVerification: EmploymentVerification[];
  /**
   * The mode under which the analysis was conducted.
   */
  analysisMode: 'active' | 'passive' | string;
  /**
   * Recommended depth of technical interviewing based on confidence and flags.
   */
  recommendedInterviewDepth: 'deep' | 'standard' | 'light' | string;
}

/**
 * Section B: Tech Stack & Language Evidence.
 * Details the technologies claimed by the candidate versus the concrete evidence found in public commits.
 */
export interface SectionB {
  /**
   * Details of languages used, matching self-claims against concrete repository evidence.
   */
  languages: LanguageEvidence[];
  /**
   * Details of frameworks analyzed, claimed, and evidenced.
   */
  frameworks: FrameworkEvidence[];
  /**
   * Details of cloud and server infrastructure technologies used or configured.
   */
  infrastructure: InfrastructureEvidence[];
  /**
   * List of specific technologies or skills claimed by the candidate for which no evidence was found.
   */
  zeroEvidenceClaims: string[];
}

/**
 * Section C: Qualitative Engineering Dimensions & Trajectories.
 * Explores deep qualitative patterns found across the codebase.
 */
export interface SectionC {
  /**
   * Evaluation of coding throughput, delivery speed, and cadence.
   */
  shippingVelocity: QualitativeDimension;
  /**
   * Evaluation of testing patterns, code standards, CI/CD discipline, and lint compliance over time.
   */
  qualityDisciplineTrajectory: QualitativeDimension;
  /**
   * Assessment of community interactions, PR discussions, review behavior, and collaborative patterns.
   */
  collaborationStyle: QualitativeDimension;
  /**
   * Concrete patterns demonstrating how the candidate utilizes AI systems (e.g., auto-gen comments, co-author tags).
   */
  aiLeverageEvidence: QualitativeDimension;
  /**
   * Qualitative evaluation of documentation, code comments, pull request descriptions, and commit messages.
   */
  communicationQuality: QualitativeDimension;
}

/**
 * Section D: Verification, Integrity, & Anti-Gaming.
 * Identifies anomalies, credential leaks, and missing pieces of information that require human verification.
 */
export interface SectionD {
  /**
   * Detected system gaming or anti-pattern flags.
   */
  flags: AntiGamingFlag[];
  /**
   * Areas where public signals are entirely blind or inconsistent.
   */
  verificationGaps: string[];
  /**
   * Whether a hard credential leak (e.g., API keys, passwords) was found in public commit history.
   */
  credentialLeakDetected: boolean;
}

/**
 * Section E: Structured Interview Guide.
 * Generates custom interview questions to target verified gaps, flags, and technical capabilities.
 */
export interface SectionE {
  /**
   * Core technical questions targeting the candidate's claimed deep expertise.
   */
  technicalQuestions: Array<{
    question: string;
    rationale: string;
  }>;
  /**
   * Targeted questions designed to probe areas of observability gaps.
   */
  gapProbes: Array<{
    question: string;
    gap: string;
  }>;
  /**
   * Critical questions to probe potential gaming/anti-pattern flags detected in Section D.
   */
  flagProbes: Array<{
    question: string;
    flagType: AntiGamingFlag['type'];
  }>;
  /**
   * Suggested characteristics, background, or seniority of the optimal technical interviewer pairing.
   */
  suggestedInterviewerPairing: string;
}

/**
 * Section F: Job Description Alignment & Overlap.
 * Optional section evaluating the candidate against a specific Job Description target.
 */
export interface SectionF {
  /**
   * Calculated percentage or alignment score (0 to 100) representing match to the Job Description.
   */
  overlapScore: number;
  /**
   * Specific skills or signals in the candidate's profile matching the Job Description.
   */
  matchedSignals: string[];
  /**
   * Critical requirements in the Job Description missing from the candidate's public footprint.
   */
  gapSignals: string[];
  /**
   * Summary of the Job Description's key intent and required archetype.
   */
  jdIntentSummary: string;
}

/**
 * Section G: Epistemic Boundaries & Validation Routing.
 * Establishes limits of what the system can assert based on public signals and maps specific questions to these limits.
 */
export interface SectionG {
  /**
   * Explicit statements of what the model cannot verify due to technical or signal boundaries.
   */
  epistemicBoundaries: string[];
  /**
   * Specific interview probes mapped directly to the corresponding epistemic boundary.
   */
  routedProbes: Array<{
    boundary: string;
    probe: string;
  }>;
}

/**
 * PrimitivesBlock containing P1 through P7 core assessments.
 */
export interface PrimitivesBlock {
  /**
   * P1: Shipping Velocity assessment.
   */
  P1: PrimitiveAssessment;
  /**
   * P2: Code Quality / Quality Discipline assessment.
   */
  P2: PrimitiveAssessment;
  /**
   * P3: Collaboration Style & Code Review assessment.
   */
  P3: PrimitiveAssessment;
  /**
   * P4: AI Leverage assessment.
   */
  P4: PrimitiveAssessment;
  /**
   * P5: Communication Quality (documentation, commit messages) assessment.
   */
  P5: PrimitiveAssessment;
  /**
   * P6: Technical Complexity & Architecture Design assessment.
   */
  P6: PrimitiveAssessment;
  /**
   * P7: Domain Specialization & Language Fluency assessment.
   */
  P7: PrimitiveAssessment;
}

/**
 * Meta information containing data about the analysis process and targets.
 */
export interface MetaBlock {
  /**
   * The mode under which the analysis was run ('active' or 'passive').
   */
  analysisMode: 'active' | 'passive' | string;
  /**
   * The targeted engineering seniority level (e.g., 'Senior', 'Staff', 'Mid').
   */
  seniorityTarget: string;
  /**
   * The targeted engineering operating archetype.
   */
  archetypeTarget: string;
  /**
   * The date and time when the Evidence Brief was generated.
   */
  generatedAt: string | Date;
  /**
   * Total number of repositories analyzed during this assessment.
   */
  reposAnalysed: number;
  /**
   * Total number of repositories successfully cloned for deep AST/history review (optional).
   */
  reposCloned?: number;
  /**
   * The qualification gate passed by this profile (e.g., 'level_3_gate', 'standard_entry').
   */
  profileLevelGate: string | number;
}

/**
 * Complete contract representing a verified 16Signals Evidence Brief for a candidate.
 * It is structured into seven primary sections (A-G), a dedicated primitives block (P1-P7), and a meta block.
 */
export interface EvidenceBrief {
  /**
   * Section A: Core Profile & Capabilities Summary.
   */
  sectionA: SectionA;
  /**
   * Section B: Tech Stack & Language Evidence.
   */
  sectionB: SectionB;
  /**
   * Section C: Qualitative Engineering Dimensions & Trajectories.
   */
  sectionC: SectionC;
  /**
   * Section D: Verification, Integrity, & Anti-Gaming.
   */
  sectionD: SectionD;
  /**
   * Section E: Structured Interview Guide.
   */
  sectionE: SectionE;
  /**
   * Section F: Job Description Alignment & Overlap (Optional).
   */
  sectionF?: SectionF | null;
  /**
   * Section G: Epistemic Boundaries & Validation Routing.
   */
  sectionG: SectionG;
  /**
   * The primitives block P1-P7 containing raw quantitative and qualitative assessments.
   */
  primitives: PrimitivesBlock;
  /**
   * Metadata describing the generation settings and input boundaries.
   */
  meta: MetaBlock;
}
